import type {
  ConnectionState,
  Customer,
  DeliveryOrder,
} from './types';
import {SERVICE_TYPE_DEFAULT} from './constants';

// Thông tin nhà hàng lấy từ Thiết lập hệ thống/Thiết lập chung/Thông tin chung
export const RESTAURANT_DEFAULT = {
  name: 'Nhà hàng Phở Thìn 13 Lò Đúc',
  senderName: 'Nguyễn Thu Hằng',
  phone: '0912 345 678',
  province: 'TP. Hà Nội',
  district: 'Quận Hai Bà Trưng',
  ward: 'Phường Phạm Đình Hổ',
  address: '13 Lò Đúc',
};

export const INITIAL_CONNECTION: ConnectionState = {
  // Mặc định CHƯA kết nối — đúng luồng thật: phải vào Web quản lý › Ứng dụng để Kết nối trước.
  isConnected: false,
  info: {
    phone: RESTAURANT_DEFAULT.phone,
    province: RESTAURANT_DEFAULT.province,
    district: RESTAURANT_DEFAULT.district,
    ward: RESTAURANT_DEFAULT.ward,
    address: RESTAURANT_DEFAULT.address,
  },
  requireVatInvoice: false,
  vatEmail: '',
};

export const CUSTOMERS: Customer[] = [
  {
    id: 'kh1',
    name: 'Trần Minh Anh',
    phone: '0987 111 222',
    hasDeliveredBefore: true,
    addresses: [
      {
        id: 'a1',
        freetext: '88 Bà Triệu',
        ward: 'Phường Nguyễn Du',
        district: 'Quận Hai Bà Trưng',
        province: 'TP. Hà Nội',
        isDefault: true,
      },
    ],
  },
  {
    id: 'kh2',
    name: 'Lê Hoàng Nam',
    phone: '0988 333 444',
    hasDeliveredBefore: false,
    addresses: [
      {
        id: 'a2',
        freetext: '25 Nguyễn Trãi',
        ward: '',
        district: '',
        province: '',
        isDefault: false,
      },
    ],
  },
  {
    id: 'kh3',
    name: 'Phạm Thùy Linh',
    phone: '0905 777 888',
    hasDeliveredBefore: true,
    addresses: [
      {
        id: 'a3',
        freetext: '112 Lê Lợi',
        ward: 'Phường Bến Nghé',
        district: 'Quận 1',
        province: 'TP. Hồ Chí Minh',
        isDefault: true,
      },
    ],
  },
];

const now = '16/07/2026';

export const INITIAL_ORDERS: DeliveryOrder[] = [
  {
    id: 'o1',
    orderNo: 'DH000148',
    trackingNo: undefined,
    customerName: 'Trần Minh Anh',
    customerPhone: '0987 111 222',
    address: {
      id: 'a1',
      freetext: '88 Bà Triệu',
      ward: 'Phường Nguyễn Du',
      district: 'Quận Hai Bà Trưng',
      province: 'TP. Hà Nội',
      isDefault: true,
    },
    items: [
      {id: 'm1', name: 'Phở bò chín đặc biệt', qty: 2, price: 65000},
      {id: 'm4', name: 'Quẩy giòn', qty: 3, price: 5000},
    ],
    subtotal: 145000,
    shippingFeePartner: 18000,
    shippingFeeCustomer: 18000,
    isCod: true,
    codAmount: 163000,
    serviceType: SERVICE_TYPE_DEFAULT,
    cukcukStatus: 'cho_gui_doi_tac',
    geStatus: undefined,
    scheduledTime: '11:45 ' + now,
    createdAt: '11:20 ' + now,
    note: 'Giao giờ trưa, gọi trước khi tới',
  },
  {
    id: 'o2',
    orderNo: 'DH000149',
    trackingNo: 'GE-8842193017',
    customerName: 'Phạm Thùy Linh',
    customerPhone: '0905 777 888',
    address: {
      id: 'a3',
      freetext: '112 Lê Lợi',
      ward: 'Phường Bến Nghé',
      district: 'Quận 1',
      province: 'TP. Hồ Chí Minh',
      isDefault: true,
    },
    items: [{id: 'm2', name: 'Phở bò tái lăn', qty: 1, price: 70000}],
    subtotal: 70000,
    shippingFeePartner: 22000,
    shippingFeeCustomer: 25000,
    isCod: true,
    codAmount: 95000,
    serviceType: SERVICE_TYPE_DEFAULT,
    cukcukStatus: 'cho_giao_hang',
    geStatus: 'ALLOCATING',
    geStatusUpdatedAt: '11:36 ' + now,
    scheduledTime: '12:10 ' + now,
    createdAt: '11:35 ' + now,
  },
  {
    id: 'o3',
    orderNo: 'DH000150',
    invoiceNo: 'HD00151',
    trackingNo: 'GE-8842193044',
    customerName: 'Trần Minh Anh',
    customerPhone: '0987 111 222',
    address: {
      id: 'a1',
      freetext: '88 Bà Triệu',
      ward: 'Phường Nguyễn Du',
      district: 'Quận Hai Bà Trưng',
      province: 'TP. Hà Nội',
      isDefault: true,
    },
    items: [
      {id: 'm3', name: 'Phở gà ta', qty: 2, price: 60000},
      {id: 'm6', name: 'Nước cam ép', qty: 2, price: 35000},
    ],
    subtotal: 190000,
    shippingFeePartner: 20000,
    shippingFeeCustomer: 20000,
    isCod: true,
    codAmount: 210000,
    serviceType: SERVICE_TYPE_DEFAULT,
    cukcukStatus: 'dang_giao_hang',
    geStatus: 'IN_DELIVERY',
    geStatusUpdatedAt: '12:02 ' + now,
    driverName: 'Nguyễn Văn Hùng',
    driverPhone: '0977 234 561',
    scheduledTime: '12:30 ' + now,
    createdAt: '11:50 ' + now,
  },
  {
    id: 'o4',
    orderNo: 'DH000145',
    invoiceNo: 'HD00147',
    trackingNo: 'GE-8842192880',
    customerName: 'Phạm Thùy Linh',
    customerPhone: '0905 777 888',
    address: {
      id: 'a3',
      freetext: '112 Lê Lợi',
      ward: 'Phường Bến Nghé',
      district: 'Quận 1',
      province: 'TP. Hồ Chí Minh',
      isDefault: true,
    },
    items: [{id: 'm1', name: 'Phở bò chín đặc biệt', qty: 3, price: 65000}],
    subtotal: 195000,
    shippingFeePartner: 24000,
    shippingFeeCustomer: 24000,
    isCod: true,
    codAmount: 219000,
    serviceType: SERVICE_TYPE_DEFAULT,
    cukcukStatus: 'da_thanh_toan',
    geStatus: 'COMPLETED',
    geStatusUpdatedAt: '10:41 ' + now,
    driverName: 'Trần Quốc Bảo',
    driverPhone: '0983 456 789',
    scheduledTime: '10:15 ' + now,
    createdAt: '09:40 ' + now,
  },
];
