import pathlib
from check_graph import load_graph, _PREFIX

def _module_of(path):
    parts = path.split("/"); return parts[1] if len(parts) > 2 and parts[0]=="modules" else path

def render_ownership(g) -> str:
    rows = []
    for n in g.nodes.values():
        for e in n.relations:
            if e.type == "owns":
                rows.append((f"{e.target_file}#{e.target_anchor}", _module_of(n.path)))
    rows.sort()
    out = ["<!-- GENERATED by gen_views.py from `owns` edges — DO NOT HAND-EDIT -->",
           "# Ownership map (generated)", "", "| Concept | Owner |", "|---|---|"]
    out += [f"| `{c}` | {o} |" for c, o in rows]
    return "\n".join(out) + "\n"

def render_prefixes(g) -> str:
    rows = []
    for n in g.nodes.values():
        for e in n.relations:
            if e.type == "owns" and e.target_anchor and _PREFIX.match(e.target_anchor):
                rows.append((e.target_anchor, _module_of(n.path)))
    rows.sort()
    out = ["<!-- GENERATED by gen_views.py from `owns` edges — DO NOT HAND-EDIT -->",
           "# Prefix map (generated)", "", "| Prefix | Owner |", "|---|---|"]
    out += [f"| `{p}` | {o} |" for p, o in rows]
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "specs"
    g = load_graph(root)
    outdir = pathlib.Path(root) / "registry" / "_views"
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "ownership-map.md").write_text(render_ownership(g), encoding="utf-8")
    print(f"wrote {outdir/'ownership-map.md'}")
    (outdir / "prefixes.md").write_text(render_prefixes(g), encoding="utf-8")
    print(f"wrote {outdir/'prefixes.md'}")
